apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: session-db
  namespace: auth
spec:
  serviceName: session-db
  replicas: 1
  selector:
    matchLabels:
      app: session-db
  template:
    metadata:
      labels:
        app: session-db
    spec:
      containers:
        - name: session-db
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: session-db
  namespace: auth
spec:
  selector:
    app: session-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP