apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth
type: Opaque
data:
  DATASOURCE_PASSWORD: bHBxdzcyaEtTSndud2o4
  LOGIN_TOKEN_DB_PASSWORD: MQ==
  JWT_SECRET: ODVmN2RkMjRjN2UyNGM0NGM5MDk4ODc0MjQ2NWRkYTM1Yzc1ZjQwMjg2ZWQ0ZmE1NjZhM2E4ZmQ1YzBkYWVmZQ==
  JWT_EXPIRATION: NjMwNzIwMDAwMDA=
  RECAPTCHA_SECRET_KEY: NkxmZUJYd2ZBQUFBQUdJOEVNeXl5U2MzaUVLN2pTUXFiVUdrODVFLQ==
