apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-config
data:
  DB_URL: jdbc:postgresql://finance-db.default.svc.cluster.local:5432/finance_db
  DB_NAME: finance_db
  DB_USER: global_user
  DB_PASSWORD: a11cfe739SKSWob621a0
  JWT_SECRET: 85f7dd24c7e24c44c90988742465dda35c75f40286ed4fa566a3a8fd5c0daefe
  JWT_EXPIRATION: "63072000000"
  BROKER_HOST: kafka-broker.default.svc.cluster.local:9092
  CACHE_REDIS_HOST: redis-cache.default.svc.cluster.local
  CACHE_REDIS_PORT: "6379"