// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currency.proto

package com.bombulis.stock.control.proto;

public final class Currency {
  private Currency() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CurrencyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bombulis.accounting.proto.CurrencyRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string isoCode = 1;</code>
     * @return The isoCode.
     */
    java.lang.String getIsoCode();
    /**
     * <code>string isoCode = 1;</code>
     * @return The bytes for isoCode.
     */
    com.google.protobuf.ByteString
        getIsoCodeBytes();
  }
  /**
   * Protobuf type {@code com.bombulis.accounting.proto.CurrencyRequest}
   */
  public  static final class CurrencyRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bombulis.accounting.proto.CurrencyRequest)
      CurrencyRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CurrencyRequest.newBuilder() to construct.
    private CurrencyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CurrencyRequest() {
      isoCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CurrencyRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CurrencyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              isoCode_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bombulis.stock.control.proto.Currency.internal_static_com_bombulis_accounting_proto_CurrencyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bombulis.stock.control.proto.Currency.internal_static_com_bombulis_accounting_proto_CurrencyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bombulis.stock.control.proto.Currency.CurrencyRequest.class, com.bombulis.stock.control.proto.Currency.CurrencyRequest.Builder.class);
    }

    public static final int ISOCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object isoCode_;
    /**
     * <code>string isoCode = 1;</code>
     * @return The isoCode.
     */
    public java.lang.String getIsoCode() {
      java.lang.Object ref = isoCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isoCode_ = s;
        return s;
      }
    }
    /**
     * <code>string isoCode = 1;</code>
     * @return The bytes for isoCode.
     */
    public com.google.protobuf.ByteString
        getIsoCodeBytes() {
      java.lang.Object ref = isoCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isoCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIsoCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, isoCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIsoCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, isoCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bombulis.stock.control.proto.Currency.CurrencyRequest)) {
        return super.equals(obj);
      }
      com.bombulis.stock.control.proto.Currency.CurrencyRequest other = (com.bombulis.stock.control.proto.Currency.CurrencyRequest) obj;

      if (!getIsoCode()
          .equals(other.getIsoCode())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ISOCODE_FIELD_NUMBER;
      hash = (53 * hash) + getIsoCode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bombulis.stock.control.proto.Currency.CurrencyRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bombulis.accounting.proto.CurrencyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bombulis.accounting.proto.CurrencyRequest)
        com.bombulis.stock.control.proto.Currency.CurrencyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bombulis.stock.control.proto.Currency.internal_static_com_bombulis_accounting_proto_CurrencyRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bombulis.stock.control.proto.Currency.internal_static_com_bombulis_accounting_proto_CurrencyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bombulis.stock.control.proto.Currency.CurrencyRequest.class, com.bombulis.stock.control.proto.Currency.CurrencyRequest.Builder.class);
      }

      // Construct using com.bombulis.stock.control.proto.Currency.CurrencyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isoCode_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bombulis.stock.control.proto.Currency.internal_static_com_bombulis_accounting_proto_CurrencyRequest_descriptor;
      }

      @java.lang.Override
      public com.bombulis.stock.control.proto.Currency.CurrencyRequest getDefaultInstanceForType() {
        return com.bombulis.stock.control.proto.Currency.CurrencyRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.bombulis.stock.control.proto.Currency.CurrencyRequest build() {
        com.bombulis.stock.control.proto.Currency.CurrencyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bombulis.stock.control.proto.Currency.CurrencyRequest buildPartial() {
        com.bombulis.stock.control.proto.Currency.CurrencyRequest result = new com.bombulis.stock.control.proto.Currency.CurrencyRequest(this);
        result.isoCode_ = isoCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bombulis.stock.control.proto.Currency.CurrencyRequest) {
          return mergeFrom((com.bombulis.stock.control.proto.Currency.CurrencyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bombulis.stock.control.proto.Currency.CurrencyRequest other) {
        if (other == com.bombulis.stock.control.proto.Currency.CurrencyRequest.getDefaultInstance()) return this;
        if (!other.getIsoCode().isEmpty()) {
          isoCode_ = other.isoCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bombulis.stock.control.proto.Currency.CurrencyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bombulis.stock.control.proto.Currency.CurrencyRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object isoCode_ = "";
      /**
       * <code>string isoCode = 1;</code>
       * @return The isoCode.
       */
      public java.lang.String getIsoCode() {
        java.lang.Object ref = isoCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          isoCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string isoCode = 1;</code>
       * @return The bytes for isoCode.
       */
      public com.google.protobuf.ByteString
          getIsoCodeBytes() {
        java.lang.Object ref = isoCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isoCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string isoCode = 1;</code>
       * @param value The isoCode to set.
       * @return This builder for chaining.
       */
      public Builder setIsoCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isoCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string isoCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsoCode() {
        
        isoCode_ = getDefaultInstance().getIsoCode();
        onChanged();
        return this;
      }
      /**
       * <code>string isoCode = 1;</code>
       * @param value The bytes for isoCode to set.
       * @return This builder for chaining.
       */
      public Builder setIsoCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isoCode_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bombulis.accounting.proto.CurrencyRequest)
    }

    // @@protoc_insertion_point(class_scope:com.bombulis.accounting.proto.CurrencyRequest)
    private static final com.bombulis.stock.control.proto.Currency.CurrencyRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bombulis.stock.control.proto.Currency.CurrencyRequest();
    }

    public static com.bombulis.stock.control.proto.Currency.CurrencyRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CurrencyRequest>
        PARSER = new com.google.protobuf.AbstractParser<CurrencyRequest>() {
      @java.lang.Override
      public CurrencyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CurrencyRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CurrencyRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CurrencyRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bombulis.stock.control.proto.Currency.CurrencyRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CurrencyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bombulis.accounting.proto.CurrencyResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currencyId = 1;</code>
     * @return The currencyId.
     */
    java.lang.String getCurrencyId();
    /**
     * <code>string currencyId = 1;</code>
     * @return The bytes for currencyId.
     */
    com.google.protobuf.ByteString
        getCurrencyIdBytes();

    /**
     * <code>string isoCode = 2;</code>
     * @return The isoCode.
     */
    java.lang.String getIsoCode();
    /**
     * <code>string isoCode = 2;</code>
     * @return The bytes for isoCode.
     */
    com.google.protobuf.ByteString
        getIsoCodeBytes();

    /**
     * <code>string numericCode = 3;</code>
     * @return The numericCode.
     */
    java.lang.String getNumericCode();
    /**
     * <code>string numericCode = 3;</code>
     * @return The bytes for numericCode.
     */
    com.google.protobuf.ByteString
        getNumericCodeBytes();
  }
  /**
   * Protobuf type {@code com.bombulis.accounting.proto.CurrencyResponse}
   */
  public  static final class CurrencyResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bombulis.accounting.proto.CurrencyResponse)
      CurrencyResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CurrencyResponse.newBuilder() to construct.
    private CurrencyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CurrencyResponse() {
      currencyId_ = "";
      isoCode_ = "";
      numericCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CurrencyResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CurrencyResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currencyId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              isoCode_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              numericCode_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bombulis.stock.control.proto.Currency.internal_static_com_bombulis_accounting_proto_CurrencyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bombulis.stock.control.proto.Currency.internal_static_com_bombulis_accounting_proto_CurrencyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bombulis.stock.control.proto.Currency.CurrencyResponse.class, com.bombulis.stock.control.proto.Currency.CurrencyResponse.Builder.class);
    }

    public static final int CURRENCYID_FIELD_NUMBER = 1;
    private volatile java.lang.Object currencyId_;
    /**
     * <code>string currencyId = 1;</code>
     * @return The currencyId.
     */
    public java.lang.String getCurrencyId() {
      java.lang.Object ref = currencyId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyId_ = s;
        return s;
      }
    }
    /**
     * <code>string currencyId = 1;</code>
     * @return The bytes for currencyId.
     */
    public com.google.protobuf.ByteString
        getCurrencyIdBytes() {
      java.lang.Object ref = currencyId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISOCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object isoCode_;
    /**
     * <code>string isoCode = 2;</code>
     * @return The isoCode.
     */
    public java.lang.String getIsoCode() {
      java.lang.Object ref = isoCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isoCode_ = s;
        return s;
      }
    }
    /**
     * <code>string isoCode = 2;</code>
     * @return The bytes for isoCode.
     */
    public com.google.protobuf.ByteString
        getIsoCodeBytes() {
      java.lang.Object ref = isoCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isoCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMERICCODE_FIELD_NUMBER = 3;
    private volatile java.lang.Object numericCode_;
    /**
     * <code>string numericCode = 3;</code>
     * @return The numericCode.
     */
    public java.lang.String getNumericCode() {
      java.lang.Object ref = numericCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        numericCode_ = s;
        return s;
      }
    }
    /**
     * <code>string numericCode = 3;</code>
     * @return The bytes for numericCode.
     */
    public com.google.protobuf.ByteString
        getNumericCodeBytes() {
      java.lang.Object ref = numericCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        numericCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurrencyIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currencyId_);
      }
      if (!getIsoCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, isoCode_);
      }
      if (!getNumericCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, numericCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurrencyIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currencyId_);
      }
      if (!getIsoCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, isoCode_);
      }
      if (!getNumericCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, numericCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bombulis.stock.control.proto.Currency.CurrencyResponse)) {
        return super.equals(obj);
      }
      com.bombulis.stock.control.proto.Currency.CurrencyResponse other = (com.bombulis.stock.control.proto.Currency.CurrencyResponse) obj;

      if (!getCurrencyId()
          .equals(other.getCurrencyId())) return false;
      if (!getIsoCode()
          .equals(other.getIsoCode())) return false;
      if (!getNumericCode()
          .equals(other.getNumericCode())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCYID_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyId().hashCode();
      hash = (37 * hash) + ISOCODE_FIELD_NUMBER;
      hash = (53 * hash) + getIsoCode().hashCode();
      hash = (37 * hash) + NUMERICCODE_FIELD_NUMBER;
      hash = (53 * hash) + getNumericCode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bombulis.stock.control.proto.Currency.CurrencyResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bombulis.accounting.proto.CurrencyResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bombulis.accounting.proto.CurrencyResponse)
        com.bombulis.stock.control.proto.Currency.CurrencyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bombulis.stock.control.proto.Currency.internal_static_com_bombulis_accounting_proto_CurrencyResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bombulis.stock.control.proto.Currency.internal_static_com_bombulis_accounting_proto_CurrencyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bombulis.stock.control.proto.Currency.CurrencyResponse.class, com.bombulis.stock.control.proto.Currency.CurrencyResponse.Builder.class);
      }

      // Construct using com.bombulis.stock.control.proto.Currency.CurrencyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currencyId_ = "";

        isoCode_ = "";

        numericCode_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bombulis.stock.control.proto.Currency.internal_static_com_bombulis_accounting_proto_CurrencyResponse_descriptor;
      }

      @java.lang.Override
      public com.bombulis.stock.control.proto.Currency.CurrencyResponse getDefaultInstanceForType() {
        return com.bombulis.stock.control.proto.Currency.CurrencyResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.bombulis.stock.control.proto.Currency.CurrencyResponse build() {
        com.bombulis.stock.control.proto.Currency.CurrencyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bombulis.stock.control.proto.Currency.CurrencyResponse buildPartial() {
        com.bombulis.stock.control.proto.Currency.CurrencyResponse result = new com.bombulis.stock.control.proto.Currency.CurrencyResponse(this);
        result.currencyId_ = currencyId_;
        result.isoCode_ = isoCode_;
        result.numericCode_ = numericCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bombulis.stock.control.proto.Currency.CurrencyResponse) {
          return mergeFrom((com.bombulis.stock.control.proto.Currency.CurrencyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bombulis.stock.control.proto.Currency.CurrencyResponse other) {
        if (other == com.bombulis.stock.control.proto.Currency.CurrencyResponse.getDefaultInstance()) return this;
        if (!other.getCurrencyId().isEmpty()) {
          currencyId_ = other.currencyId_;
          onChanged();
        }
        if (!other.getIsoCode().isEmpty()) {
          isoCode_ = other.isoCode_;
          onChanged();
        }
        if (!other.getNumericCode().isEmpty()) {
          numericCode_ = other.numericCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bombulis.stock.control.proto.Currency.CurrencyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bombulis.stock.control.proto.Currency.CurrencyResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object currencyId_ = "";
      /**
       * <code>string currencyId = 1;</code>
       * @return The currencyId.
       */
      public java.lang.String getCurrencyId() {
        java.lang.Object ref = currencyId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currencyId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currencyId = 1;</code>
       * @return The bytes for currencyId.
       */
      public com.google.protobuf.ByteString
          getCurrencyIdBytes() {
        java.lang.Object ref = currencyId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencyId = 1;</code>
       * @param value The currencyId to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencyId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyId() {
        
        currencyId_ = getDefaultInstance().getCurrencyId();
        onChanged();
        return this;
      }
      /**
       * <code>string currencyId = 1;</code>
       * @param value The bytes for currencyId to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencyId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object isoCode_ = "";
      /**
       * <code>string isoCode = 2;</code>
       * @return The isoCode.
       */
      public java.lang.String getIsoCode() {
        java.lang.Object ref = isoCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          isoCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string isoCode = 2;</code>
       * @return The bytes for isoCode.
       */
      public com.google.protobuf.ByteString
          getIsoCodeBytes() {
        java.lang.Object ref = isoCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isoCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string isoCode = 2;</code>
       * @param value The isoCode to set.
       * @return This builder for chaining.
       */
      public Builder setIsoCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isoCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string isoCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsoCode() {
        
        isoCode_ = getDefaultInstance().getIsoCode();
        onChanged();
        return this;
      }
      /**
       * <code>string isoCode = 2;</code>
       * @param value The bytes for isoCode to set.
       * @return This builder for chaining.
       */
      public Builder setIsoCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isoCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object numericCode_ = "";
      /**
       * <code>string numericCode = 3;</code>
       * @return The numericCode.
       */
      public java.lang.String getNumericCode() {
        java.lang.Object ref = numericCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          numericCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string numericCode = 3;</code>
       * @return The bytes for numericCode.
       */
      public com.google.protobuf.ByteString
          getNumericCodeBytes() {
        java.lang.Object ref = numericCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          numericCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string numericCode = 3;</code>
       * @param value The numericCode to set.
       * @return This builder for chaining.
       */
      public Builder setNumericCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        numericCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string numericCode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumericCode() {
        
        numericCode_ = getDefaultInstance().getNumericCode();
        onChanged();
        return this;
      }
      /**
       * <code>string numericCode = 3;</code>
       * @param value The bytes for numericCode to set.
       * @return This builder for chaining.
       */
      public Builder setNumericCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        numericCode_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bombulis.accounting.proto.CurrencyResponse)
    }

    // @@protoc_insertion_point(class_scope:com.bombulis.accounting.proto.CurrencyResponse)
    private static final com.bombulis.stock.control.proto.Currency.CurrencyResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bombulis.stock.control.proto.Currency.CurrencyResponse();
    }

    public static com.bombulis.stock.control.proto.Currency.CurrencyResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CurrencyResponse>
        PARSER = new com.google.protobuf.AbstractParser<CurrencyResponse>() {
      @java.lang.Override
      public CurrencyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CurrencyResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CurrencyResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CurrencyResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bombulis.stock.control.proto.Currency.CurrencyResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bombulis_accounting_proto_CurrencyRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bombulis_accounting_proto_CurrencyRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bombulis_accounting_proto_CurrencyResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bombulis_accounting_proto_CurrencyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016currency.proto\022\035com.bombulis.accountin" +
      "g.proto\"\"\n\017CurrencyRequest\022\017\n\007isoCode\030\001 " +
      "\001(\t\"L\n\020CurrencyResponse\022\022\n\ncurrencyId\030\001 " +
      "\001(\t\022\017\n\007isoCode\030\002 \001(\t\022\023\n\013numericCode\030\003 \001(" +
      "\t2\205\001\n\017CurrencyService\022r\n\017GetCurrencyInfo" +
      "\022..com.bombulis.accounting.proto.Currenc" +
      "yRequest\032/.com.bombulis.accounting.proto" +
      ".CurrencyResponseB\"\n com.bombulis.stock." +
      "control.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bombulis_accounting_proto_CurrencyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bombulis_accounting_proto_CurrencyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bombulis_accounting_proto_CurrencyRequest_descriptor,
        new java.lang.String[] { "IsoCode", });
    internal_static_com_bombulis_accounting_proto_CurrencyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bombulis_accounting_proto_CurrencyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bombulis_accounting_proto_CurrencyResponse_descriptor,
        new java.lang.String[] { "CurrencyId", "IsoCode", "NumericCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
