name: Build and Push Docker image for finance

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]

jobs:
  build-finance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image for Finance
        uses: docker/build-push-action@v2
        with:
          context: ./accounting
          dockerfile: ./accounting/Dockerfile
          push: true
          tags: |
            rabserkon/finance:latest
            rabserkon/finance:${{ github.sha }}

  build-authentication:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image for Authentication
        uses: docker/build-push-action@v2
        with:
          context: ./authentication-management-module
          dockerfile: ./authentication-management-module/Dockerfile
          push: true
          tags: |
            rabserkon/authentication:latest
            rabserkon/authentication:${{ github.sha }}