// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package com.bombulis.accounting.proto;

public final class Transaction {
  private Transaction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Тип операции
   * </pre>
   *
   * Protobuf enum {@code com.bombulis.accounting.proto.OperationType}
   */
  public enum OperationType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Списание
     * </pre>
     *
     * <code>BUY = 0;</code>
     */
    BUY(0),
    /**
     * <pre>
     * Пополнение
     * </pre>
     *
     * <code>SELL = 1;</code>
     */
    SELL(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Списание
     * </pre>
     *
     * <code>BUY = 0;</code>
     */
    public static final int BUY_VALUE = 0;
    /**
     * <pre>
     * Пополнение
     * </pre>
     *
     * <code>SELL = 1;</code>
     */
    public static final int SELL_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OperationType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OperationType forNumber(int value) {
      switch (value) {
        case 0: return BUY;
        case 1: return SELL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OperationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OperationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OperationType>() {
            public OperationType findValueByNumber(int number) {
              return OperationType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bombulis.accounting.proto.Transaction.getDescriptor().getEnumTypes().get(0);
    }

    private static final OperationType[] VALUES = values();

    public static OperationType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OperationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.bombulis.accounting.proto.OperationType)
  }

  public interface TransactionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bombulis.accounting.proto.TransactionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Номер аккаунта
     * </pre>
     *
     * <code>string account_id = 1;</code>
     * @return The accountId.
     */
    java.lang.String getAccountId();
    /**
     * <pre>
     * Номер аккаунта
     * </pre>
     *
     * <code>string account_id = 1;</code>
     * @return The bytes for accountId.
     */
    com.google.protobuf.ByteString
        getAccountIdBytes();

    /**
     * <pre>
     * Валюта аккаунта (например, "USD", "EUR")
     * </pre>
     *
     * <code>string currency = 2;</code>
     * @return The currency.
     */
    java.lang.String getCurrency();
    /**
     * <pre>
     * Валюта аккаунта (например, "USD", "EUR")
     * </pre>
     *
     * <code>string currency = 2;</code>
     * @return The bytes for currency.
     */
    com.google.protobuf.ByteString
        getCurrencyBytes();

    /**
     * <pre>
     * Сумма операции
     * </pre>
     *
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    double getAmount();

    /**
     * <pre>
     * Комментарий операции
     * </pre>
     *
     * <code>string comment = 4;</code>
     * @return The comment.
     */
    java.lang.String getComment();
    /**
     * <pre>
     * Комментарий операции
     * </pre>
     *
     * <code>string comment = 4;</code>
     * @return The bytes for comment.
     */
    com.google.protobuf.ByteString
        getCommentBytes();

    /**
     * <pre>
     * Тип операции (СПИСАНИЕ или ПОПОЛНЕНИЕ)
     * </pre>
     *
     * <code>.com.bombulis.accounting.proto.OperationType operation = 5;</code>
     * @return The enum numeric value on the wire for operation.
     */
    int getOperationValue();
    /**
     * <pre>
     * Тип операции (СПИСАНИЕ или ПОПОЛНЕНИЕ)
     * </pre>
     *
     * <code>.com.bombulis.accounting.proto.OperationType operation = 5;</code>
     * @return The operation.
     */
    com.bombulis.accounting.proto.Transaction.OperationType getOperation();

    /**
     * <pre>
     *Id пользователя
     * </pre>
     *
     * <code>string user_id = 6;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <pre>
     *Id пользователя
     * </pre>
     *
     * <code>string user_id = 6;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string broker_account_id = 7;</code>
     * @return The brokerAccountId.
     */
    java.lang.String getBrokerAccountId();
    /**
     * <code>string broker_account_id = 7;</code>
     * @return The bytes for brokerAccountId.
     */
    com.google.protobuf.ByteString
        getBrokerAccountIdBytes();

    /**
     * <code>string equity_account_id = 8;</code>
     * @return The equityAccountId.
     */
    java.lang.String getEquityAccountId();
    /**
     * <code>string equity_account_id = 8;</code>
     * @return The bytes for equityAccountId.
     */
    com.google.protobuf.ByteString
        getEquityAccountIdBytes();

    /**
     * <pre>
     * Дата операции
     * </pre>
     *
     * <code>.google.protobuf.Timestamp date = 9;</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <pre>
     * Дата операции
     * </pre>
     *
     * <code>.google.protobuf.Timestamp date = 9;</code>
     * @return The date.
     */
    com.google.protobuf.Timestamp getDate();
    /**
     * <pre>
     * Дата операции
     * </pre>
     *
     * <code>.google.protobuf.Timestamp date = 9;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateOrBuilder();
  }
  /**
   * Protobuf type {@code com.bombulis.accounting.proto.TransactionRequest}
   */
  public  static final class TransactionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bombulis.accounting.proto.TransactionRequest)
      TransactionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransactionRequest.newBuilder() to construct.
    private TransactionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionRequest() {
      accountId_ = "";
      currency_ = "";
      comment_ = "";
      operation_ = 0;
      userId_ = "";
      brokerAccountId_ = "";
      equityAccountId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransactionRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              accountId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              currency_ = s;
              break;
            }
            case 25: {

              amount_ = input.readDouble();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              comment_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              operation_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              brokerAccountId_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              equityAccountId_ = s;
              break;
            }
            case 74: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (date_ != null) {
                subBuilder = date_.toBuilder();
              }
              date_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(date_);
                date_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bombulis.accounting.proto.Transaction.internal_static_com_bombulis_accounting_proto_TransactionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bombulis.accounting.proto.Transaction.internal_static_com_bombulis_accounting_proto_TransactionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bombulis.accounting.proto.Transaction.TransactionRequest.class, com.bombulis.accounting.proto.Transaction.TransactionRequest.Builder.class);
    }

    public static final int ACCOUNT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object accountId_;
    /**
     * <pre>
     * Номер аккаунта
     * </pre>
     *
     * <code>string account_id = 1;</code>
     * @return The accountId.
     */
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Номер аккаунта
     * </pre>
     *
     * <code>string account_id = 1;</code>
     * @return The bytes for accountId.
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENCY_FIELD_NUMBER = 2;
    private volatile java.lang.Object currency_;
    /**
     * <pre>
     * Валюта аккаунта (например, "USD", "EUR")
     * </pre>
     *
     * <code>string currency = 2;</code>
     * @return The currency.
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Валюта аккаунта (например, "USD", "EUR")
     * </pre>
     *
     * <code>string currency = 2;</code>
     * @return The bytes for currency.
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private double amount_;
    /**
     * <pre>
     * Сумма операции
     * </pre>
     *
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    public double getAmount() {
      return amount_;
    }

    public static final int COMMENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object comment_;
    /**
     * <pre>
     * Комментарий операции
     * </pre>
     *
     * <code>string comment = 4;</code>
     * @return The comment.
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comment_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Комментарий операции
     * </pre>
     *
     * <code>string comment = 4;</code>
     * @return The bytes for comment.
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATION_FIELD_NUMBER = 5;
    private int operation_;
    /**
     * <pre>
     * Тип операции (СПИСАНИЕ или ПОПОЛНЕНИЕ)
     * </pre>
     *
     * <code>.com.bombulis.accounting.proto.OperationType operation = 5;</code>
     * @return The enum numeric value on the wire for operation.
     */
    public int getOperationValue() {
      return operation_;
    }
    /**
     * <pre>
     * Тип операции (СПИСАНИЕ или ПОПОЛНЕНИЕ)
     * </pre>
     *
     * <code>.com.bombulis.accounting.proto.OperationType operation = 5;</code>
     * @return The operation.
     */
    public com.bombulis.accounting.proto.Transaction.OperationType getOperation() {
      @SuppressWarnings("deprecation")
      com.bombulis.accounting.proto.Transaction.OperationType result = com.bombulis.accounting.proto.Transaction.OperationType.valueOf(operation_);
      return result == null ? com.bombulis.accounting.proto.Transaction.OperationType.UNRECOGNIZED : result;
    }

    public static final int USER_ID_FIELD_NUMBER = 6;
    private volatile java.lang.Object userId_;
    /**
     * <pre>
     *Id пользователя
     * </pre>
     *
     * <code>string user_id = 6;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *Id пользователя
     * </pre>
     *
     * <code>string user_id = 6;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BROKER_ACCOUNT_ID_FIELD_NUMBER = 7;
    private volatile java.lang.Object brokerAccountId_;
    /**
     * <code>string broker_account_id = 7;</code>
     * @return The brokerAccountId.
     */
    public java.lang.String getBrokerAccountId() {
      java.lang.Object ref = brokerAccountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brokerAccountId_ = s;
        return s;
      }
    }
    /**
     * <code>string broker_account_id = 7;</code>
     * @return The bytes for brokerAccountId.
     */
    public com.google.protobuf.ByteString
        getBrokerAccountIdBytes() {
      java.lang.Object ref = brokerAccountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brokerAccountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EQUITY_ACCOUNT_ID_FIELD_NUMBER = 8;
    private volatile java.lang.Object equityAccountId_;
    /**
     * <code>string equity_account_id = 8;</code>
     * @return The equityAccountId.
     */
    public java.lang.String getEquityAccountId() {
      java.lang.Object ref = equityAccountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        equityAccountId_ = s;
        return s;
      }
    }
    /**
     * <code>string equity_account_id = 8;</code>
     * @return The bytes for equityAccountId.
     */
    public com.google.protobuf.ByteString
        getEquityAccountIdBytes() {
      java.lang.Object ref = equityAccountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        equityAccountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 9;
    private com.google.protobuf.Timestamp date_;
    /**
     * <pre>
     * Дата операции
     * </pre>
     *
     * <code>.google.protobuf.Timestamp date = 9;</code>
     * @return Whether the date field is set.
     */
    public boolean hasDate() {
      return date_ != null;
    }
    /**
     * <pre>
     * Дата операции
     * </pre>
     *
     * <code>.google.protobuf.Timestamp date = 9;</code>
     * @return The date.
     */
    public com.google.protobuf.Timestamp getDate() {
      return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
    }
    /**
     * <pre>
     * Дата операции
     * </pre>
     *
     * <code>.google.protobuf.Timestamp date = 9;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
      return getDate();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAccountIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountId_);
      }
      if (!getCurrencyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currency_);
      }
      if (amount_ != 0D) {
        output.writeDouble(3, amount_);
      }
      if (!getCommentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, comment_);
      }
      if (operation_ != com.bombulis.accounting.proto.Transaction.OperationType.BUY.getNumber()) {
        output.writeEnum(5, operation_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userId_);
      }
      if (!getBrokerAccountIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, brokerAccountId_);
      }
      if (!getEquityAccountIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, equityAccountId_);
      }
      if (date_ != null) {
        output.writeMessage(9, getDate());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAccountIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountId_);
      }
      if (!getCurrencyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currency_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amount_);
      }
      if (!getCommentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, comment_);
      }
      if (operation_ != com.bombulis.accounting.proto.Transaction.OperationType.BUY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, operation_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userId_);
      }
      if (!getBrokerAccountIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, brokerAccountId_);
      }
      if (!getEquityAccountIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, equityAccountId_);
      }
      if (date_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getDate());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bombulis.accounting.proto.Transaction.TransactionRequest)) {
        return super.equals(obj);
      }
      com.bombulis.accounting.proto.Transaction.TransactionRequest other = (com.bombulis.accounting.proto.Transaction.TransactionRequest) obj;

      if (!getAccountId()
          .equals(other.getAccountId())) return false;
      if (!getCurrency()
          .equals(other.getCurrency())) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (!getComment()
          .equals(other.getComment())) return false;
      if (operation_ != other.operation_) return false;
      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getBrokerAccountId()
          .equals(other.getBrokerAccountId())) return false;
      if (!getEquityAccountId()
          .equals(other.getEquityAccountId())) return false;
      if (hasDate() != other.hasDate()) return false;
      if (hasDate()) {
        if (!getDate()
            .equals(other.getDate())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAccountId().hashCode();
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getCurrency().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + COMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getComment().hashCode();
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + operation_;
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + BROKER_ACCOUNT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBrokerAccountId().hashCode();
      hash = (37 * hash) + EQUITY_ACCOUNT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEquityAccountId().hashCode();
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bombulis.accounting.proto.Transaction.TransactionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bombulis.accounting.proto.Transaction.TransactionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bombulis.accounting.proto.TransactionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bombulis.accounting.proto.TransactionRequest)
        com.bombulis.accounting.proto.Transaction.TransactionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bombulis.accounting.proto.Transaction.internal_static_com_bombulis_accounting_proto_TransactionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bombulis.accounting.proto.Transaction.internal_static_com_bombulis_accounting_proto_TransactionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bombulis.accounting.proto.Transaction.TransactionRequest.class, com.bombulis.accounting.proto.Transaction.TransactionRequest.Builder.class);
      }

      // Construct using com.bombulis.accounting.proto.Transaction.TransactionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        accountId_ = "";

        currency_ = "";

        amount_ = 0D;

        comment_ = "";

        operation_ = 0;

        userId_ = "";

        brokerAccountId_ = "";

        equityAccountId_ = "";

        if (dateBuilder_ == null) {
          date_ = null;
        } else {
          date_ = null;
          dateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bombulis.accounting.proto.Transaction.internal_static_com_bombulis_accounting_proto_TransactionRequest_descriptor;
      }

      @java.lang.Override
      public com.bombulis.accounting.proto.Transaction.TransactionRequest getDefaultInstanceForType() {
        return com.bombulis.accounting.proto.Transaction.TransactionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.bombulis.accounting.proto.Transaction.TransactionRequest build() {
        com.bombulis.accounting.proto.Transaction.TransactionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bombulis.accounting.proto.Transaction.TransactionRequest buildPartial() {
        com.bombulis.accounting.proto.Transaction.TransactionRequest result = new com.bombulis.accounting.proto.Transaction.TransactionRequest(this);
        result.accountId_ = accountId_;
        result.currency_ = currency_;
        result.amount_ = amount_;
        result.comment_ = comment_;
        result.operation_ = operation_;
        result.userId_ = userId_;
        result.brokerAccountId_ = brokerAccountId_;
        result.equityAccountId_ = equityAccountId_;
        if (dateBuilder_ == null) {
          result.date_ = date_;
        } else {
          result.date_ = dateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bombulis.accounting.proto.Transaction.TransactionRequest) {
          return mergeFrom((com.bombulis.accounting.proto.Transaction.TransactionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bombulis.accounting.proto.Transaction.TransactionRequest other) {
        if (other == com.bombulis.accounting.proto.Transaction.TransactionRequest.getDefaultInstance()) return this;
        if (!other.getAccountId().isEmpty()) {
          accountId_ = other.accountId_;
          onChanged();
        }
        if (!other.getCurrency().isEmpty()) {
          currency_ = other.currency_;
          onChanged();
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (!other.getComment().isEmpty()) {
          comment_ = other.comment_;
          onChanged();
        }
        if (other.operation_ != 0) {
          setOperationValue(other.getOperationValue());
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getBrokerAccountId().isEmpty()) {
          brokerAccountId_ = other.brokerAccountId_;
          onChanged();
        }
        if (!other.getEquityAccountId().isEmpty()) {
          equityAccountId_ = other.equityAccountId_;
          onChanged();
        }
        if (other.hasDate()) {
          mergeDate(other.getDate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bombulis.accounting.proto.Transaction.TransactionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bombulis.accounting.proto.Transaction.TransactionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object accountId_ = "";
      /**
       * <pre>
       * Номер аккаунта
       * </pre>
       *
       * <code>string account_id = 1;</code>
       * @return The accountId.
       */
      public java.lang.String getAccountId() {
        java.lang.Object ref = accountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Номер аккаунта
       * </pre>
       *
       * <code>string account_id = 1;</code>
       * @return The bytes for accountId.
       */
      public com.google.protobuf.ByteString
          getAccountIdBytes() {
        java.lang.Object ref = accountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Номер аккаунта
       * </pre>
       *
       * <code>string account_id = 1;</code>
       * @param value The accountId to set.
       * @return This builder for chaining.
       */
      public Builder setAccountId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Номер аккаунта
       * </pre>
       *
       * <code>string account_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountId() {
        
        accountId_ = getDefaultInstance().getAccountId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Номер аккаунта
       * </pre>
       *
       * <code>string account_id = 1;</code>
       * @param value The bytes for accountId to set.
       * @return This builder for chaining.
       */
      public Builder setAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accountId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currency_ = "";
      /**
       * <pre>
       * Валюта аккаунта (например, "USD", "EUR")
       * </pre>
       *
       * <code>string currency = 2;</code>
       * @return The currency.
       */
      public java.lang.String getCurrency() {
        java.lang.Object ref = currency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currency_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Валюта аккаунта (например, "USD", "EUR")
       * </pre>
       *
       * <code>string currency = 2;</code>
       * @return The bytes for currency.
       */
      public com.google.protobuf.ByteString
          getCurrencyBytes() {
        java.lang.Object ref = currency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Валюта аккаунта (например, "USD", "EUR")
       * </pre>
       *
       * <code>string currency = 2;</code>
       * @param value The currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrency(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Валюта аккаунта (например, "USD", "EUR")
       * </pre>
       *
       * <code>string currency = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrency() {
        
        currency_ = getDefaultInstance().getCurrency();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Валюта аккаунта (например, "USD", "EUR")
       * </pre>
       *
       * <code>string currency = 2;</code>
       * @param value The bytes for currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currency_ = value;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <pre>
       * Сумма операции
       * </pre>
       *
       * <code>double amount = 3;</code>
       * @return The amount.
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <pre>
       * Сумма операции
       * </pre>
       *
       * <code>double amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Сумма операции
       * </pre>
       *
       * <code>double amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object comment_ = "";
      /**
       * <pre>
       * Комментарий операции
       * </pre>
       *
       * <code>string comment = 4;</code>
       * @return The comment.
       */
      public java.lang.String getComment() {
        java.lang.Object ref = comment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          comment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Комментарий операции
       * </pre>
       *
       * <code>string comment = 4;</code>
       * @return The bytes for comment.
       */
      public com.google.protobuf.ByteString
          getCommentBytes() {
        java.lang.Object ref = comment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Комментарий операции
       * </pre>
       *
       * <code>string comment = 4;</code>
       * @param value The comment to set.
       * @return This builder for chaining.
       */
      public Builder setComment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        comment_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Комментарий операции
       * </pre>
       *
       * <code>string comment = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearComment() {
        
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Комментарий операции
       * </pre>
       *
       * <code>string comment = 4;</code>
       * @param value The bytes for comment to set.
       * @return This builder for chaining.
       */
      public Builder setCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        comment_ = value;
        onChanged();
        return this;
      }

      private int operation_ = 0;
      /**
       * <pre>
       * Тип операции (СПИСАНИЕ или ПОПОЛНЕНИЕ)
       * </pre>
       *
       * <code>.com.bombulis.accounting.proto.OperationType operation = 5;</code>
       * @return The enum numeric value on the wire for operation.
       */
      public int getOperationValue() {
        return operation_;
      }
      /**
       * <pre>
       * Тип операции (СПИСАНИЕ или ПОПОЛНЕНИЕ)
       * </pre>
       *
       * <code>.com.bombulis.accounting.proto.OperationType operation = 5;</code>
       * @param value The enum numeric value on the wire for operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperationValue(int value) {
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Тип операции (СПИСАНИЕ или ПОПОЛНЕНИЕ)
       * </pre>
       *
       * <code>.com.bombulis.accounting.proto.OperationType operation = 5;</code>
       * @return The operation.
       */
      public com.bombulis.accounting.proto.Transaction.OperationType getOperation() {
        @SuppressWarnings("deprecation")
        com.bombulis.accounting.proto.Transaction.OperationType result = com.bombulis.accounting.proto.Transaction.OperationType.valueOf(operation_);
        return result == null ? com.bombulis.accounting.proto.Transaction.OperationType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Тип операции (СПИСАНИЕ или ПОПОЛНЕНИЕ)
       * </pre>
       *
       * <code>.com.bombulis.accounting.proto.OperationType operation = 5;</code>
       * @param value The operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperation(com.bombulis.accounting.proto.Transaction.OperationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        operation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Тип операции (СПИСАНИЕ или ПОПОЛНЕНИЕ)
       * </pre>
       *
       * <code>.com.bombulis.accounting.proto.OperationType operation = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperation() {
        
        operation_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <pre>
       *Id пользователя
       * </pre>
       *
       * <code>string user_id = 6;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *Id пользователя
       * </pre>
       *
       * <code>string user_id = 6;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Id пользователя
       * </pre>
       *
       * <code>string user_id = 6;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Id пользователя
       * </pre>
       *
       * <code>string user_id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Id пользователя
       * </pre>
       *
       * <code>string user_id = 6;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object brokerAccountId_ = "";
      /**
       * <code>string broker_account_id = 7;</code>
       * @return The brokerAccountId.
       */
      public java.lang.String getBrokerAccountId() {
        java.lang.Object ref = brokerAccountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          brokerAccountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string broker_account_id = 7;</code>
       * @return The bytes for brokerAccountId.
       */
      public com.google.protobuf.ByteString
          getBrokerAccountIdBytes() {
        java.lang.Object ref = brokerAccountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brokerAccountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string broker_account_id = 7;</code>
       * @param value The brokerAccountId to set.
       * @return This builder for chaining.
       */
      public Builder setBrokerAccountId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brokerAccountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string broker_account_id = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrokerAccountId() {
        
        brokerAccountId_ = getDefaultInstance().getBrokerAccountId();
        onChanged();
        return this;
      }
      /**
       * <code>string broker_account_id = 7;</code>
       * @param value The bytes for brokerAccountId to set.
       * @return This builder for chaining.
       */
      public Builder setBrokerAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brokerAccountId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object equityAccountId_ = "";
      /**
       * <code>string equity_account_id = 8;</code>
       * @return The equityAccountId.
       */
      public java.lang.String getEquityAccountId() {
        java.lang.Object ref = equityAccountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          equityAccountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string equity_account_id = 8;</code>
       * @return The bytes for equityAccountId.
       */
      public com.google.protobuf.ByteString
          getEquityAccountIdBytes() {
        java.lang.Object ref = equityAccountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          equityAccountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string equity_account_id = 8;</code>
       * @param value The equityAccountId to set.
       * @return This builder for chaining.
       */
      public Builder setEquityAccountId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        equityAccountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string equity_account_id = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEquityAccountId() {
        
        equityAccountId_ = getDefaultInstance().getEquityAccountId();
        onChanged();
        return this;
      }
      /**
       * <code>string equity_account_id = 8;</code>
       * @param value The bytes for equityAccountId to set.
       * @return This builder for chaining.
       */
      public Builder setEquityAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        equityAccountId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp date_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateBuilder_;
      /**
       * <pre>
       * Дата операции
       * </pre>
       *
       * <code>.google.protobuf.Timestamp date = 9;</code>
       * @return Whether the date field is set.
       */
      public boolean hasDate() {
        return dateBuilder_ != null || date_ != null;
      }
      /**
       * <pre>
       * Дата операции
       * </pre>
       *
       * <code>.google.protobuf.Timestamp date = 9;</code>
       * @return The date.
       */
      public com.google.protobuf.Timestamp getDate() {
        if (dateBuilder_ == null) {
          return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        } else {
          return dateBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Дата операции
       * </pre>
       *
       * <code>.google.protobuf.Timestamp date = 9;</code>
       */
      public Builder setDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          date_ = value;
          onChanged();
        } else {
          dateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Дата операции
       * </pre>
       *
       * <code>.google.protobuf.Timestamp date = 9;</code>
       */
      public Builder setDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateBuilder_ == null) {
          date_ = builderForValue.build();
          onChanged();
        } else {
          dateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Дата операции
       * </pre>
       *
       * <code>.google.protobuf.Timestamp date = 9;</code>
       */
      public Builder mergeDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (date_ != null) {
            date_ =
              com.google.protobuf.Timestamp.newBuilder(date_).mergeFrom(value).buildPartial();
          } else {
            date_ = value;
          }
          onChanged();
        } else {
          dateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Дата операции
       * </pre>
       *
       * <code>.google.protobuf.Timestamp date = 9;</code>
       */
      public Builder clearDate() {
        if (dateBuilder_ == null) {
          date_ = null;
          onChanged();
        } else {
          date_ = null;
          dateBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Дата операции
       * </pre>
       *
       * <code>.google.protobuf.Timestamp date = 9;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateBuilder() {
        
        onChanged();
        return getDateFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Дата операции
       * </pre>
       *
       * <code>.google.protobuf.Timestamp date = 9;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
        if (dateBuilder_ != null) {
          return dateBuilder_.getMessageOrBuilder();
        } else {
          return date_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        }
      }
      /**
       * <pre>
       * Дата операции
       * </pre>
       *
       * <code>.google.protobuf.Timestamp date = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateFieldBuilder() {
        if (dateBuilder_ == null) {
          dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDate(),
                  getParentForChildren(),
                  isClean());
          date_ = null;
        }
        return dateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bombulis.accounting.proto.TransactionRequest)
    }

    // @@protoc_insertion_point(class_scope:com.bombulis.accounting.proto.TransactionRequest)
    private static final com.bombulis.accounting.proto.Transaction.TransactionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bombulis.accounting.proto.Transaction.TransactionRequest();
    }

    public static com.bombulis.accounting.proto.Transaction.TransactionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionRequest>
        PARSER = new com.google.protobuf.AbstractParser<TransactionRequest>() {
      @java.lang.Override
      public TransactionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bombulis.accounting.proto.Transaction.TransactionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransactionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bombulis.accounting.proto.TransactionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Успех операции
     * </pre>
     *
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <pre>
     * Сообщение (например, описание ошибки)
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * Сообщение (например, описание ошибки)
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * Сообщение для ответа на запрос
   * </pre>
   *
   * Protobuf type {@code com.bombulis.accounting.proto.TransactionResponse}
   */
  public  static final class TransactionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bombulis.accounting.proto.TransactionResponse)
      TransactionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransactionResponse.newBuilder() to construct.
    private TransactionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionResponse() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransactionResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bombulis.accounting.proto.Transaction.internal_static_com_bombulis_accounting_proto_TransactionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bombulis.accounting.proto.Transaction.internal_static_com_bombulis_accounting_proto_TransactionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bombulis.accounting.proto.Transaction.TransactionResponse.class, com.bombulis.accounting.proto.Transaction.TransactionResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <pre>
     * Успех операции
     * </pre>
     *
     * <code>bool success = 1;</code>
     * @return The success.
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * Сообщение (например, описание ошибки)
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Сообщение (например, описание ошибки)
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bombulis.accounting.proto.Transaction.TransactionResponse)) {
        return super.equals(obj);
      }
      com.bombulis.accounting.proto.Transaction.TransactionResponse other = (com.bombulis.accounting.proto.Transaction.TransactionResponse) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bombulis.accounting.proto.Transaction.TransactionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bombulis.accounting.proto.Transaction.TransactionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bombulis.accounting.proto.Transaction.TransactionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Сообщение для ответа на запрос
     * </pre>
     *
     * Protobuf type {@code com.bombulis.accounting.proto.TransactionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bombulis.accounting.proto.TransactionResponse)
        com.bombulis.accounting.proto.Transaction.TransactionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bombulis.accounting.proto.Transaction.internal_static_com_bombulis_accounting_proto_TransactionResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bombulis.accounting.proto.Transaction.internal_static_com_bombulis_accounting_proto_TransactionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bombulis.accounting.proto.Transaction.TransactionResponse.class, com.bombulis.accounting.proto.Transaction.TransactionResponse.Builder.class);
      }

      // Construct using com.bombulis.accounting.proto.Transaction.TransactionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bombulis.accounting.proto.Transaction.internal_static_com_bombulis_accounting_proto_TransactionResponse_descriptor;
      }

      @java.lang.Override
      public com.bombulis.accounting.proto.Transaction.TransactionResponse getDefaultInstanceForType() {
        return com.bombulis.accounting.proto.Transaction.TransactionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.bombulis.accounting.proto.Transaction.TransactionResponse build() {
        com.bombulis.accounting.proto.Transaction.TransactionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bombulis.accounting.proto.Transaction.TransactionResponse buildPartial() {
        com.bombulis.accounting.proto.Transaction.TransactionResponse result = new com.bombulis.accounting.proto.Transaction.TransactionResponse(this);
        result.success_ = success_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bombulis.accounting.proto.Transaction.TransactionResponse) {
          return mergeFrom((com.bombulis.accounting.proto.Transaction.TransactionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bombulis.accounting.proto.Transaction.TransactionResponse other) {
        if (other == com.bombulis.accounting.proto.Transaction.TransactionResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bombulis.accounting.proto.Transaction.TransactionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bombulis.accounting.proto.Transaction.TransactionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <pre>
       * Успех операции
       * </pre>
       *
       * <code>bool success = 1;</code>
       * @return The success.
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <pre>
       * Успех операции
       * </pre>
       *
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Успех операции
       * </pre>
       *
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * Сообщение (например, описание ошибки)
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Сообщение (например, описание ошибки)
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Сообщение (например, описание ошибки)
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Сообщение (например, описание ошибки)
       * </pre>
       *
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Сообщение (например, описание ошибки)
       * </pre>
       *
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bombulis.accounting.proto.TransactionResponse)
    }

    // @@protoc_insertion_point(class_scope:com.bombulis.accounting.proto.TransactionResponse)
    private static final com.bombulis.accounting.proto.Transaction.TransactionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bombulis.accounting.proto.Transaction.TransactionResponse();
    }

    public static com.bombulis.accounting.proto.Transaction.TransactionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionResponse>
        PARSER = new com.google.protobuf.AbstractParser<TransactionResponse>() {
      @java.lang.Override
      public TransactionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bombulis.accounting.proto.Transaction.TransactionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bombulis_accounting_proto_TransactionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bombulis_accounting_proto_TransactionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bombulis_accounting_proto_TransactionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bombulis_accounting_proto_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021transaction.proto\022\035com.bombulis.accoun" +
      "ting.proto\032\037google/protobuf/timestamp.pr" +
      "oto\"\215\002\n\022TransactionRequest\022\022\n\naccount_id" +
      "\030\001 \001(\t\022\020\n\010currency\030\002 \001(\t\022\016\n\006amount\030\003 \001(\001" +
      "\022\017\n\007comment\030\004 \001(\t\022?\n\toperation\030\005 \001(\0162,.c" +
      "om.bombulis.accounting.proto.OperationTy" +
      "pe\022\017\n\007user_id\030\006 \001(\t\022\031\n\021broker_account_id" +
      "\030\007 \001(\t\022\031\n\021equity_account_id\030\010 \001(\t\022(\n\004dat" +
      "e\030\t \001(\0132\032.google.protobuf.Timestamp\"7\n\023T" +
      "ransactionResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007m" +
      "essage\030\002 \001(\t*\"\n\rOperationType\022\007\n\003BUY\020\000\022\010" +
      "\n\004SELL\020\0012\204\001\n\022TransactionService\022n\n\005Debit" +
      "\0221.com.bombulis.accounting.proto.Transac" +
      "tionRequest\0322.com.bombulis.accounting.pr" +
      "oto.TransactionResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_bombulis_accounting_proto_TransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bombulis_accounting_proto_TransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bombulis_accounting_proto_TransactionRequest_descriptor,
        new java.lang.String[] { "AccountId", "Currency", "Amount", "Comment", "Operation", "UserId", "BrokerAccountId", "EquityAccountId", "Date", });
    internal_static_com_bombulis_accounting_proto_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bombulis_accounting_proto_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bombulis_accounting_proto_TransactionResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
